---
- name: Installing Homebrew Packages
  homebrew:
    name: "{{ item }}"
    state: "present"
  with_items: 
    - "autoenv"
    - "cmake"
    - "dep"
    - "yarn"


- name: Installing Homebrew Cask Packages
  homebrew_cask:
    name: "{{ item }}"
    state: "present"
  with_items:     
    - "android-studio"
    - "atom"
    - "docker"
    - "github"
    - "java8"
    - "visual-studio-code"
    - "sourcetree"
